### ISSUE TITLE
font

### ISSUE THREAD

**Issue by yunyit** [yunyit/yunyit.github.io#5]
# Description
font family and size to make sure hovers works well across platform

# Tasks
- [x] zh font - all platform
- [x] font size re-assessment

**Comment by yunyit** [comment]
- [ ] comment's en 'let's chat' to smaller font
