### ISSUE TITLE
website icon

### ISSUE THREAD

**Issue by yunyit** [yunyit/yunyit.github.io#6]
# Description
website icon needed for tabs

# Tasks
- [ ] find/create a web icon img
- [ ] set it up for the website
- [ ] but not the front page left top corner
